
version: '3.8'

# Services
services:

  # Nginx Service
  # comment for using host nginx service
  nginx:
    image: nginx:1.23
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/php
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  # PHP Service
  php:
    #image: php:8.2-fpm
    build: ./.docker/php
    #comment for communication between containers using internal port 
    #ports:
    #  - 9000:9000
    working_dir: /var/www/php
    volumes:
      - ./src:/var/www/php
    depends_on:
      mysql:
        condition: service_healthy

  # MySQL Service
  mysql:
    image: mysql/mysql-server:8.0.31
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: BBI@2022db 
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: nursing_stress 
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./init:/docker-entrypoint-initdb.d
      - ./database/mysql:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10

  # PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.0
    ports:
      - 80:80
    environment:
      PMA_HOST: mysql
      #comment for no sub folder
      #PMA_ABSOLUTE_URI: "http://127.0.0.1/phpmyadmin/"
    volumes:
      - ./.docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    depends_on:
      mysql:
        condition: service_healthy

  # Volumes
  #volumes:
